server:
  port: 9000
  address: localhost
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.170.153:3306/yeyue?useSSL=false&characterEncoding=utf-8&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: Yeyue19961016.
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.yeyue.pictureshare.model
wechat:
  appid: wx51649937382aba39
  appsecret: 701d68b27313a21a783a80d3e5e5cd2d
  granttype: authorization_code
  url: https://api.weixin.qq.com/sns/jscode2session
qiniu:
  accesskey: awwdMzulXYy62PLsvP4O99sIAXIZl0k80UFxrKag
  secretkey: E6M4BnR_l_D0R1QQK-kjsWC0QCb9HyvSZLVefPzx
  bucket: picshare-wxchat
  path: icshare-wxchat.henghengya.cn.qiniudns.com
